config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
  post 'cusotmers/guest_sign_in'=>'public/sessions#guest_sign_in'
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 会員用
  scope module: :public do
    get 'searches/search'=>'searches#search', as: 'search'

    get 'gears/search'=>'gears#search', as: 'gear_search'
    resources :gears, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :gear_reviews, only: [:new, :create, :destroy]
    end

    get 'camps/search'=>'camps#search', as: 'camp_search'
    resources :camps, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :camp_reviews, only: [:new, :create, :destroy]
    end

    resources :customers, only: [:show, :edit, :update]
    get 'customers/:id/camps'=>'customers#camp', as: 'my_page'
    get 'customers/:id/unsubscribe'=>'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/:id/withdraw'=>'customers#withdraw', as: 'withdraw'

    root :to =>"homes#top"
  end

  # 管理者用
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    get 'admin/customers/:id/camps'=>'customers#camp', as: 'my_page'

    resources :tags, only: [:index]

    resources :categories, only: [:create, :edit, :update]

    resources :areas, only: [:create, :edit, :update]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :camps,        dependent: :destroy
  has_many :camp_reviews, dependent: :destroy
  has_many :gears,        dependent: :destroy
  has_many :gear_reviews, dependent: :destroy

  validates :name, presence: true, length: { minimum: 1, maximum: 10 }, uniqueness: true,
    format: {with:/\A[ぁ-んァ-ン一-龥]/,message: "は、ひらがな、カタカナ、漢字のどれかで入力して下さい"}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/profile_icon.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(name: 'ゲストユーザー', email: 'guest@example') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "ゲストユーザー"
    end
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
    @camp_reviews = @customer.camp_reviews
    @gear_reviews = @customer.gear_reviews
  end

  def camp
    @customer = Customer.find(params[:id])
    @camps = @customer.camps
    @gears = @customer.gears
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id), notice: "会員情報を編集しました。"
    else
      flash.now[:alert] = "会員情報を更新できませんでした。"
      render 'edit'
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :is_active)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/camp.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <h5 class="my-4 px-3"><b><%= @customer.name %>さんの会員詳細</b></h5>
  </div>
  <div class="row">
    <div class="col-md-4">
      <table class="table table-borderless">
        <tr>
          <td><b>会員ID</b></td>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <td><b>ニックネーム</b></td>
          <td><%= @customer.name %></td>
        </tr>
        <tr>
          <td><b>メールアドレス</b></td>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <td><b>会員ステータス</b></td>
          <% if @customer.is_active == true %>
            <td class="text-success"><b>有効</b></td>
          <% else %>
            <td class="text-danger"><b>退会</b></td>
          <% end %>
        </tr>
        <tr>
          <td><b><%= link_to '編集する', edit_admin_customer_path(@customer.id), class: "btn btn-success" %></b></td>
          <td><%= link_to "レビュー一覽", admin_customer_path(@customer.id), class: "btn btn-primary" %></td>
        </tr>
      </table>
    </div>

    <div class="col-md-8">
      <div class="container">
        <div class="row">
          <div class="col-sm-6">
            <h5 class="text-center" style="background-color: #eee; width:260px; margin-bottom: 40px;"><b>投稿したキャンプ場</b></h5>
              <% @camps.each do |camp| %>
              <div class="row mt-3 ml-3">
                <%= link_to camp_path(camp.id), class: 'text-dark' do %>
                  <u><%= camp.name %></u>
                <% end %>
              </div>
              <hr>
              <% end %>
          </div>
        <!--会員のキャンプギアレビュー一覽-->
          <div class="col-sm-6">
          <h5 class="text-center" style="background-color: #eee; width:260px; margin-bottom: 40px;"><b>投稿したキャンプギア</b></h5>
            <% @gears.each do |gear| %>
            <div class="row mt-3 ml-3">
              <%= link_to gear_path(gear.id), class: 'text-dark' do %>
                <u><%= gear.name %></u>
              <% end %>
            </div>
            <hr>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/edit.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <h5 class="my-4 pl-3 text-center", style="margin-bottom: 40px;"><b><%= @customer.name %>さんの会員情報編集</b></h5>
  </div>
  <div class="row d-flex justify-content-center">
    <%= render "admin/shared/error_messages", resource: @customer %>
  </div>
  <div class="row d-flex justify-content-center">
      <%= form_with model: @customer, url: admin_customer_path(@customer.id) do |f| %>
      <table class="table table-borderless">
        <tbody>
        <tr>
          <th><b>会員ID</b></th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th><b>ニックネーム</b></th>
          <td><%= f.text_field :name %></b></td>
        </tr>
        <tr>
          <th><b>メールアドレス</b></th>
          <th><%= f.text_field :email %></td>
        </tr>
        <tr>
          <th><b>会員ステータス</b></th>
          <td>
            <%= f.radio_button :is_active, :true %><%= f.label :is_active, "有効" %>
            <%= f.radio_button :is_active, :false %><%= f.label :is_active, "退会" %>
          </td>
        </tr>
        <tr>
          <td><%= f.submit '変更を保存', class: 'btn btn-success' %></td>
          <td><%= link_to "戻る", admin_customer_path(@customer.id), class: 'btn btn-info' %></td>
        </tr>
        </tbody>
      </table>
      <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row px-2">
    <h5 class="mt-3 text-center", style="background-color: #eee; width:150px; margin-bottom: 40px;"><b>会員一覧</b></h5>
  </div>
  <div class="row d-flex justify-content-center">
    <table class="table table-sm", style="width: 80%;">
      <thead class="table-info">
        <th class="text-center", style="white-space: nowrap;">会員ID</th>
        <th class="text-center", style="white-space: nowrap;">ニックネーム</th>
        <th class="text-center", style="white-space: nowrap;">メールアドレス</th>
        <th class="text-center", style="white-space: nowrap;">ステータス</th>
      </thead>
      <% @customers.each do |customer| %>
      <tbody>
        <tr>
          <td class="text-center"><%= customer.id %></td>
          <td class="text-center">
            <%= link_to admin_customer_path(customer.id), class: 'text-dark' do %>
              <u><%= customer.name %></u>
            <% end %>
          </td>
          <td class="text-center"><%= customer.email %></td>
          <% if customer.is_active == true %>
            <td class="text-success text-center">有効</td>
          <% else %>
            <td class="text-danger text-center">退会</td>
          <% end %>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
  <div class="row">
    <div class="d-flex justify-content-center">
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <h5 class="my-4 px-3"><b><%= @customer.name %>さんの会員詳細</b></h5>
  </div>
  <div class="row">
    <div class="col-md-4">
      <table class="table table-borderless">
        <tr>
          <td><b>会員ID</b></td>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <td><b>ニックネーム</b></td>
          <td><%= @customer.name %></td>
        </tr>
        <tr>
          <td><b>メールアドレス</b></td>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <td><b>会員ステータス</b></td>
          <% if @customer.is_active == true %>
            <td class="text-success"><b>有効</b></td>
          <% else %>
            <td class="text-danger"><b>退会</b></td>
          <% end %>
        </tr>
        <tr>
          <td><%= link_to '編集する', edit_admin_customer_path(@customer.id), class: "btn btn-success" %></td>
          <td><%= link_to "投稿一覽", admin_my_page_path(@customer.id), class: "btn btn-primary" %></td>
        </tr>
      </table>
    </div>

    <div class="col-md-8">
      <div class="container">
        <div class="row">
          <div class="col-sm-6">
            <h5 class="text-center" style="background-color: #eee; width:260px; margin-bottom: 40px;"><b>レビューしたキャンプ場</b></h5>
            <table>
            <% @camp_reviews.each do |review| %>
              <tr>
                <td>
                  <%= link_to camp_path(review.camp.id), class: 'text-dark' do %>
                    <u><%= review.camp.name %></u>
                  <% end %>
                </td>
              </tr>
              <tr>
                <td>
                  <div id="star-rate<%= review.id%>"></div>
                </td>
                <script>
                $(document).on('turbolinks:load', function() {
                  $('#star-rate<%= review.id %>').empty();
                  $('#star-rate<%= review.id%>').raty({
                    size      : 36,
                    starOff   : '<%= asset_path('star-off.png') %>',
                    starOn    : '<%= asset_path('star-on.png') %>',
                    starHalf  : '<%= asset_path('star-half.png') %>',
                    half      : true,
                    readOnly  : true,
                    score: '<%= review.rate %>',
                  });
                });
                </script>
              </tr>
              <tr>
                <td><b><%= review.title %></b></td>
              </tr>
              <tr>
                <td>
                  <div class="border-bottom">
                    <%= safe_join(review.review.split("\n"),tag(:br)) %>
                  </div>
                </td>
              </tr>
            <% end %>
            </table>
          </div>
        <!--会員のキャンプギアレビュー一覽-->
          <div class="col-sm-6">
          <h5 class="text-center" style="background-color: #eee; width:260px; margin-bottom: 40px;"><b>レビューしたキャンプギア</b></h5>
          <table>
          <% @gear_reviews.each do |review| %>
            <tr>
              <td>
                <%= link_to gear_path(review.gear.id), class: 'text-dark' do %>
                  <u><%= review.gear.name %></u>
                <% end %>
              </td>
            </tr>
            <tr>
              <td>
                <div id="rate<%= review.id%>"></div>
              </td>
              <script>
              $(document).on('turbolinks:load', function() {
                $('#rate<%= review.id %>').empty();
                $('#rate<%= review.id %>').raty({
                  size      : 36,
                  starOff   : '<%= asset_path('star-off.png') %>',
                  starOn    : '<%= asset_path('star-on.png') %>',
                  starHalf  : '<%= asset_path('star-half.png') %>',
                  half      : true,
                  readOnly  : true,
                  score: '<%= review.rate %>',
                });
              });
              </script>
            </tr>
            <tr>
              <td><b><%= review.title %></b></td>
            </tr>
            <tr>
              <td>
                <div class="border-bottom">
                  <%= safe_join(review.review.split("\n"),tag(:br)) %>
                </div>
              </td>
            </tr>
          <% end %>
          </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>