config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
  post 'cusotmers/guest_sign_in'=>'public/sessions#guest_sign_in'
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 会員用
  scope module: :public do
    get 'searches/search'=>'searches#search', as: 'search'

    get 'gears/search'=>'gears#search', as: 'gear_search'
    resources :gears, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :gear_reviews, only: [:new, :create, :destroy]
    end

    get 'camps/search'=>'camps#search', as: 'camp_search'
    resources :camps, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :camp_reviews, only: [:new, :create, :destroy]
    end

    resources :customers, only: [:show, :edit, :update]
    get 'customers/:id/camps'=>'customers#camp', as: 'my_page'
    get 'customers/:id/unsubscribe'=>'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/:id/withdraw'=>'customers#withdraw', as: 'withdraw'

    root :to =>"homes#top"
  end

  # 管理者用
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    get 'admin/customers/:id/camps'=>'customers#camp', as: 'my_page'

    resources :tags, only: [:index]

    resources :categories, only: [:create, :edit, :update]

    resources :areas, only: [:create, :edit, :update]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @areas = Area.all
    @area = Area.new
    @categories = Category.all
    @category = Category.new
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/_area_index.html.erb
<table class="table">
  <thead style="background-color: #eee;">
    <th class="text-center">エリア名</th>
    <th></th>
  </thead>
  <% areas.each do |area| %>
  <tbody>
    <tr>
      <td><%= area.name %></td>
      <td class="d-flex justify-content-end">
        <%= link_to "編集する", edit_admin_area_path(area.id), class: 'btn btn-success' %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/admin/tags/_category_index.html.erb
<table class="table">
  <thead style="background-color: #eee;">
    <th class="text-center">カテゴリ名</th>
    <th></th>
  </thead>
  <% categories.each do |category| %>
  <tbody>
    <tr>
      <td><%= category.name %></td>
      <td class="d-flex justify-content-end">
        <%= link_to "編集する", edit_admin_category_path(category.id), class: 'btn btn-success' %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/admin/tags/index.html.erb
<div class="container px-5 my-5 px-sm-0 my-sm-0">

  <div class="row">
    <h5 class='my-4 px-3', style="background-color: #eee; width:240px;"><b>エリア・カテゴリ一覧</b></h5>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="d-flex justify-content-start">
        <h5 class='mt-3 text-center', style="background-color: #eee; width:220px; margin-bottom: 40px;"><b>エリア追加・一覧</b></h5>
      </div>
      <div class="row d-flex justify-content-center">
        <%= render "admin/shared/error_messages", resource: @area %>
        <%= form_with model: @area, url: admin_areas_path do |f| %>
          <div class="form-inline">
            <span class="mr-3"><b><%= f.label :name, 'エリア名' %></b></span>
            <span class="mr-3"><%= f.text_field :name, placeholder: "エリア名", class: 'form-control' %></span>
            <span class="mr-3"><%= f.submit '新規登録', class: 'btn btn-success' %></span>
          </div>
        <% end %>
      </div>
      <div class="mt-5">
        <%= render "admin/tags/area_index", areas: @areas %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="d-flex justify-content-start">
        <h5 class='mt-3 text-center', style="background-color: #eee; width:220px; margin-bottom: 40px;"><b>カテゴリ追加・一覧</b></h5>
      </div>
      <div class="row d-flex justify-content-center">
        <%= render "admin/shared/error_messages", resource: @category %>
        <%= form_with model: @category, url: admin_categories_path do |f| %>
          <div class="form-inline">
            <span class="mr-3"><b><%= f.label :name, 'カテゴリ名' %></b></span>
            <span class="mr-3"><%= f.text_field :name, placeholder: "カテゴリ名", class: 'form-control' %></span>
            <span class="mr-3"><%= f.submit '新規登録', class: 'btn btn-success' %></span>
          </div>
        <% end %>
      </div>
      <div class="mt-5">
        <%= render "admin/tags/category_index", categories: @categories %>
      </div>
    </div>
  </div>
</div>