config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
  post 'cusotmers/guest_sign_in'=>'public/sessions#guest_sign_in'
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 会員用
  scope module: :public do
    get 'searches/search'=>'searches#search', as: 'search'

    get 'gears/search'=>'gears#search', as: 'gear_search'
    resources :gears, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :gear_reviews, only: [:new, :create, :destroy]
    end

    get 'camps/search'=>'camps#search', as: 'camp_search'
    resources :camps, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :camp_reviews, only: [:new, :create, :destroy]
    end

    resources :customers, only: [:show, :edit, :update]
    get 'customers/:id/camps'=>'customers#camp', as: 'my_page'
    get 'customers/:id/unsubscribe'=>'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/:id/withdraw'=>'customers#withdraw', as: 'withdraw'

    root :to =>"homes#top"
  end

  # 管理者用
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    get 'admin/customers/:id/camps'=>'customers#camp', as: 'my_page'

    resources :tags, only: [:index]

    resources :categories, only: [:create, :edit, :update]

    resources :areas, only: [:create, :edit, :update]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :gears

  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin!

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_tags_path, notice: "カテゴリの登録が完了しました。"
    else
      @areas = Area.all
      @area = Area.new
      @categories = Category.all
      flash.now[:alert] = "カテゴリの登録に失敗しました。もう一度やり直してください。"
      render template: "admin/tags/index"
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_tags_path, notice: "カテゴリの更新が完了しました。"
    else
      flash.now[:alert] = "カテゴリの更新が出来ませんでした。もう一度やり直してください。"
      render 'edit'
    end
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="container">
  <div class="row">
    <h5 class='mx-5 my-5 text-center', style="background-color: #eee; width:200px; margin-bottom: 40px;"><b>カテゴリ編集</b></h5>
  </div>
  <div class="row d-flex justify-content-center">
    <%= render "admin/shared/error_messages", resource: @category %>
  </div>
  <div class="row d-flex justify-content-center">
    <%= form_with model: @category, url: admin_category_path do |f| %>
    <div class="form-group mb-2">
      <b><%= f.label :name, "カテゴリ名" %></b>
      <%= f.text_field :name, size: 30 %>
    </div>
    <div class="row d-flex justify-content-around mt-3">
      <%= f.submit "変更を保存する", class: 'btn btn-success' %>
      <%= link_to "戻る", admin_tags_path, class: "btn btn-info" %>
    </div>
    <% end %>
  </div>
</div>