config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
  post 'cusotmers/guest_sign_in'=>'public/sessions#guest_sign_in'
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 会員用
  scope module: :public do
    get 'searches/search'=>'searches#search', as: 'search'

    get 'gears/search'=>'gears#search', as: 'gear_search'
    resources :gears, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :gear_reviews, only: [:new, :create, :destroy]
    end

    get 'camps/search'=>'camps#search', as: 'camp_search'
    resources :camps, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :camp_reviews, only: [:new, :create, :destroy]
    end

    resources :customers, only: [:show, :edit, :update]
    get 'customers/:id/camps'=>'customers#camp', as: 'my_page'
    get 'customers/:id/unsubscribe'=>'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/:id/withdraw'=>'customers#withdraw', as: 'withdraw'

    root :to =>"homes#top"
  end

  # 管理者用
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    get 'admin/customers/:id/camps'=>'customers#camp', as: 'my_page'

    resources :tags, only: [:index]

    resources :categories, only: [:create, :edit, :update]

    resources :areas, only: [:create, :edit, :update]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <!--管理者がログインしているとき-->
      <% if admin_signed_in? %>
        <h2>Camposts</h2>
      <!--それ以外-->
      <% else %>
        <%= link_to root_path, class: "nav-brand text-dark" do %>
          <font size="6">Camposts</font>
        <% end %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <!--管理者がログインしているとき-->
          <% if admin_signed_in? %>
           <li class="nav-item"><%= link_to "キャンプギア一覽", gears_path, class: "nav-link btn btn-outline-dark" %></li>
           <li class="nav-item"><%= link_to "キャンプ場一覽", camps_path, class: "nav-link btn btn-outline-dark" %></li>
           <li class="nav-item"><%= link_to "会員一覽", admin_customers_path, class: "nav-link btn btn-outline-dark" %></li>
           <li class="nav-item"><%= link_to "エリア・カテゴリ一覽", admin_tags_path, class: "nav-link btn btn-outline-dark" %></li>
           <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link btn btn-outline-dark" %></li>
          <!--会員がログインしているとき-->
          <% elsif customer_signed_in? && current_customer.name != "ゲストユーザー" %>
            <li class="nav-item"><%= link_to "キャンプギア一覽", gears_path, class: "nav-link btn btn-outline-dark" %></li>
            <li class="nav-item"><%= link_to "キャンプギア投稿", new_gear_path, class: "nav-link btn btn-outline-dark" %></li>
            <li class="nav-item"><%= link_to "キャンプ場一覽", camps_path, class: "nav-link btn btn-outline-dark" %></li>
            <li class="nav-item"><%= link_to "キャンプ場投稿", new_camp_path, class: "nav-link btn btn-outline-dark" %></li>
            <li class="nav-item"><%= link_to "マイページ", customer_path(current_customer), class: "nav-link btn btn-outline-dark" %></li>
            <li class="nav-item"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link btn btn-outline-dark" %></li>
          <!--ゲストログインしているとき-->
          <% elsif customer_signed_in? && current_customer.name == "ゲストユーザー" %>
            <li class="nav-item"><%= link_to "キャンプギア一覽", gears_path, class: "btn btn-outline-dark" %></li>
            <li class="nav-item"><%= link_to "キャンプ場一覽", camps_path, class: "btn btn-outline-dark" %></li>
            <li class="nav-item"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-dark" %></li>
          <!--ログインしてないとき-->
          <% else %>
            <li class="nav-item"><%= link_to "新規会員登録", new_customer_registration_path, class: "nav-link btn btn-outline-dark" %></li>
            <li class="nav-item"><%= link_to "ゲストログイン", cusotmers_guest_sign_in_path, method: :post, class: "nav-link btn btn-outline-dark" %></li>
            <li class="nav-item"><%= link_to "ログイン", new_customer_session_path, class: "nav-link btn btn-outline-dark" %></li>
          <% end %>
        </ul>
        <!--検索窓-->
        <ul class="navbar-nav pt-1 pr-3">
          <li class="nav-item">
            <%= render 'public/searches/search' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Campost</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    </div>
    <main>
      <div class="notifications">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: key) %>
        <% end %>
      </div>
      <%= yield %>
    </main>

    <footer>
      <div class='container py-3'>
      	<div class='row my-auto d-flex justify-content-center'>
        	<p class="text-dark">Camposts</p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Campost</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <main style="height: 80vh;">
      <div class="top-bg">
        <div class="notifications">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: key) %>
          <% end %>
        </div>
        <%= yield %>
      </div>
    </main>

    <footer class="bg-light">
      <div class='container py-3'>
      	<div class='row my-auto d-flex justify-content-center'>
        	<p class="text-dark">Camposts</p>
        </div>
      </div>
    </footer>
  </body>
</html>